name: capeval
channels:
  - defaults
dependencies: 
  - attrs
  - backcall
  - blas
  - bleach
  - ca-certificates
  - certifi
  - cycler
  - dbus
  - decorator
  - defusedxml
  - entrypoints
  - expat
  - freetype
  - gettext
  - glib
  - intel-openmp
  - ipykernel
  - ipython
  - ipython_genutils
  - ipywidgets=7.5.1
  - jedi
  - jinja2
  - joblib
  - jpeg
  - jsonschema
  - jupyter=1.0.0
  - jupyter_client=5.3.3
  - jupyter_console=6.0.0
  - jupyter_core=4.5.0
  - kiwisolver
  - libedit
  - libffi
  - libiconv
  - libpng
  - libsodium
  - markupsafe
  - matplotlib=3.1.1
  - mistune
  - mkl
  - mkl-service
  - mkl_fft
  - mkl_random
  - nbconvert
  - nbformat
  - ncurses
  - notebook=6.0.1
  - numpy=1.17.2
  - numpy-base
  - openssl
  - pandas
  - pandoc
  - pandocfilters
  - parso
  - pcre
  - pexpect
  - pickleshare
  - pip
  - prometheus_client
  - prompt_toolkit
  - ptyprocess
  - pygments
  - pyparsing
  - pyqt
  - pyrsistent
  - python=3.7.4
  - python-dateutil
  - pytz
  - pyzmq
  - qt
  - qtconsole
  - readline
  - scikit-learn=0.21.3
  - scipy
  - send2trash
  - setuptools
  - sip
  - six
  - sqlite
  - terminado
  - testpath
  - tk
  - tornado
  - traitlets
  - wcwidth
  - webencodings
  - wheel
  - widgetsnbextension
  - xz
  - zeromq
  - zlib
  - pip:
    - jupyter-video-widget==0.3.1
    - ordered-namespace==2019.6.8
    - shortuuid==0.5.0
    - libgfortran
    - icud
    - appnope
    - libcxxabi
    - llvm-openmp

